#pragma once

#ifdef _MSC_VER
#define FORWARDED_EXPORT_WITH_ORDINAL(exp_name, ordinal, target_name) __pragma (comment (linker, "/export:" #exp_name "=" #target_name ",@" #ordinal))
#endif
#ifdef __GNUC__
#define FORWARDED_EXPORT_WITH_ORDINAL(exp_name, ordinal, target_name) __asm__(".section .drectve\n\t.ascii \" -export:" #exp_name "= " #target_name " @" #ordinal "\"");
#endif


FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferBlit@12, 1, console._BinkBufferBlit@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferCheckWinPos@12, 2, console._BinkBufferCheckWinPos@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferClear@8, 3, console._BinkBufferClear@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferClose@4, 4, console._BinkBufferClose@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferGetDescription@4, 5, console._BinkBufferGetDescription@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferGetError@0, 6, console._BinkBufferGetError@0)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferLock@4, 7, console._BinkBufferLock@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferOpen@16, 8, console._BinkBufferOpen@16)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetDirectDraw@8, 9, console._BinkBufferSetDirectDraw@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetHWND@8, 10, console._BinkBufferSetHWND@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetOffset@12, 11, console._BinkBufferSetOffset@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetResolution@12, 12, console._BinkBufferSetResolution@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetScale@12, 13, console._BinkBufferSetScale@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferUnlock@4, 14, console._BinkBufferUnlock@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCheckCursor@20, 15, console._BinkCheckCursor@20)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkClose@4, 16, console._BinkClose@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCloseTrack@4, 17, console._BinkCloseTrack@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCopyToBuffer@28, 18, console._BinkCopyToBuffer@28)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCopyToBufferRect@44, 19, console._BinkCopyToBufferRect@44)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDDSurfaceType@4, 20, console._BinkDDSurfaceType@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDX8SurfaceType@4, 21, console._BinkDX8SurfaceType@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDX9SurfaceType@4, 22, console._BinkDX9SurfaceType@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDoFrame@4, 23, console._BinkDoFrame@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetError@0, 24, console._BinkGetError@0)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetFrameBuffersInfo@8, 25, console._BinkGetFrameBuffersInfo@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetKeyFrame@12, 26, console._BinkGetKeyFrame@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetRealtime@12, 27, console._BinkGetRealtime@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetRects@8, 28, console._BinkGetRects@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetSummary@8, 29, console._BinkGetSummary@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackData@8, 30, console._BinkGetTrackData@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackID@8, 31, console._BinkGetTrackID@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackMaxSize@8, 32, console._BinkGetTrackMaxSize@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackType@8, 33, console._BinkGetTrackType@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGoto@12, 34, console._BinkGoto@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkIsSoftwareCursor@8, 35, console._BinkIsSoftwareCursor@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkLogoAddress@0, 36, console._BinkLogoAddress@0)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkNextFrame@4, 37, console._BinkNextFrame@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpen@8, 38, console._BinkOpen@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenDirectSound@4, 39, console._BinkOpenDirectSound@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenMiles@4, 40, console._BinkOpenMiles@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenTrack@8, 41, console._BinkOpenTrack@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenWaveOut@4, 42, console._BinkOpenWaveOut@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkPause@8, 43, console._BinkPause@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkRegisterFrameBuffers@8, 44, console._BinkRegisterFrameBuffers@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkRestoreCursor@4, 45, console._BinkRestoreCursor@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkService@4, 46, console._BinkService@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetError@4, 47, console._BinkSetError@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetFrameRate@8, 48, console._BinkSetFrameRate@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetIO@4, 49, console._BinkSetIO@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetIOSize@4, 50, console._BinkSetIOSize@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetMemory@8, 51, console._BinkSetMemory@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetMixBinVolumes@20, 52, console._BinkSetMixBinVolumes@20)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetMixBins@16, 53, console._BinkSetMixBins@16)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetPan@12, 54, console._BinkSetPan@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSimulate@4, 55, console._BinkSetSimulate@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSoundOnOff@8, 56, console._BinkSetSoundOnOff@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSoundSystem@8, 57, console._BinkSetSoundSystem@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSoundTrack@8, 58, console._BinkSetSoundTrack@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetVideoOnOff@8, 59, console._BinkSetVideoOnOff@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetVolume@12, 60, console._BinkSetVolume@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkWait@4, 61, console._BinkWait@4)